pipeline {
     agent any
         parameters {
        choice(
            choices: ['AUS' , 'EU', 'USA'],
            description: '',
            name: 'ENVIRONMENT')
         }
   
     tools {nodejs "Node16"}
  
     stages {
        stage("Build") {
             when {
                expression { 
                   return params.ENVIRONMENT == 'AUS'
                }
            }

            steps {

                sh "npm install"
                sh "npm run build"
                echo "Building to AUS"
            }
        }
        stage("Deploy") {
            steps {
                echo "deploying"
                
            }
        }
    }
}
