pipeline {
     agent any
     
     tools {nodejs "Node16"}
     
     stages {
        stage("Build") {
            steps {
                sh "npm install"
            }
        }
        stage("Deploy") {
            steps {
                echo "deploying"
                
            }
        }
    }
}
